version: '3.1'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile-db
      args:
        RESTO_PASSWORD: restopass
    restart: always
    ports:
      - 5432:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
      args:
        RESTO_HOME: /var/www/html/resto
        RESTO_PASSWORD: restopass
        PGHOST: db
        PGUSER: postgres
    restart: always
    ports:
      - 80:80
    depends_on:
      - db
